# Generated by Django 3.1.4 on 2021-01-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210121_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2021-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
